name: medix
description: "Une application pour planifier un rendez-vous médical avec un médecin."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  badges: ^3.1.2
  date_field: ^5.0.1
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  mobkit_calendar: ^0.1.3
  onesignal_flutter: ^5.1.3
  phone_form_field: ^9.1.0
  pinput: ^4.0.0
  select_form_field: ^2.2.0
  shared_preferences: ^2.2.2
  timer_count_down: ^2.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_native_splash: ^2.4.0
  path: ^1.9.0
  collapsible: ^1.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_device_id: ^1.0.1
  geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/doctors/
    - assets/icons/
    - assets/svg/
    - assets/images/
    - .env