final Map<String, String> authFR = {
  'login-to-your-account': 'Connectez-vous à votre compte',
  'your-phone-number': 'Votre numéro de téléphone',
  'phone-number-required': 'Le numéro de téléphone est requis',
  'your-password': 'Votre mot de passe',
  'password': 'Mot de passe',
  'password-not-match': 'Le mot de passe ne correspond pas',
  'password-min': 'Le mot de passe doit contenir au moins @min caractères',
  'your-birthday': 'Votre date de naissance',
  'firstname': 'Prénom',
  'your-informations': 'Vos informations',
  'create-your-account': 'Créer mon compte',
  'your-gender': 'Votre genre',
  'login-btn': 'Connexion',
  'dont-have-account': "Vous n'avez pas de compte ?",
  'login-create-account': 'Créer un compte',
  'term-and-condition':
      "J’ai lu et j’accepte la politique de confidentialité et les conditions d’utilisation.",
  'term-accepted-required-checkbox': 'Ce champ doit être coché',
  'already-registerededed': 'Déjà inscrit(e)',
  'have-account-signin': 'Se connecter',
  'something-went-wrong-title': 'Une erreur est survenue',
  'something-went-wrong': "Un problème est survenu",
  'something-went-wrong-try': "Un problème est survenu, veuillez réessayer",
  'success': 'Succès',
  'error': 'Erreur',
  'finished': 'Terminé',
  'suspended': 'Suspendu',
  'canceled': 'Annulé',
  'completed': 'Terminé',
  'login-success': 'Connexion réussie',
  'profile-update-success': 'Votre profil a été mis à jour',
  'invalid-phone-number': "Ce numéro de téléphone est invalide",
  'upload-pending': "En cours d'envoi...",
  'man': 'Homme',
  'woman': 'Femme',
  "Nouakchott": "Nouakchott",
  "Nouadhibou": "Nouadhibou",
  "Rosso": "Rosso",
  "Boghé": "Boghé",
  "Kiffa": "Kiffa",
  "Zouerate": "Zouérat",
  "Kaédi": "Kaédi",
  "Boutilimit": "Boutilimit",
  "Atar": "Atar",
  "Sélibaby": "Sélibaby",
  "Aleg": "Aleg",
  "Akjoujt": "Akjoujt",
  "Tidjikja": "Tidjikja",
  'resend': 'renvoyer',
  'resend-in': 'renvoyer dans',
  'i-did-not-receive-any-code': "je n'ai pas reçu de code?",
  'verify-your-phone-number': 'Verifié votre numéro',
  'otp-send-to-your-phone-number':
      'Un code de vérification a été transmis à votre numéro. Merci de le saisir.',
  "password-required": "Mot de passe requis",
  'password-updated': 'Mot de passe mis à jour',
  'can-not-resend-otp': 'Impossible de renvoyer le code OTP',
  'tape-otp': 'Saisir le code',
  'phone-number-already-used':
      'Le numéro de téléphone a déjà été utilisé par un autre utilisateur.',
  'are-you-sur-to-canceled': "Êtes-vous certain d'annuler votre rendez-vous?",
  'yes': 'Oui',
  'reschedule': 'Reporter',
  'reschedule-your-appointment': 'Reporter votre consultation',
  'reschedule-appointment': 'Reporter la consultation',
  'reset-your-password': 'Réinitiliser votre mot de passe',
  'forget-password': "Mot de passe oublié?",
  'reset': 'Réinitialiser',
  'appointment-reschedule-success':
      'Votre rendez-vous est reporté et attend la confirmation du médecin.',
  'appointment-delete-success': 'Votre rendez-vous a été annulé avec succès.',
  "medix-term-and-condition":
      "Conditions d’Utilisation et Politique de Confidentialité de Medix",
  "accept-term-and-condition": "1. Acceptation des Conditions",
  "if-create-account-in-medix":
      "En créant un compte sur l’application Medix, vous acceptez de vous conformer à nos conditions d’utilisation et à notre politique de confidentialité. Medix vous permet de rechercher et de réserver des rendez-vous avec des médecins de diverses spécialités.",
  "collection-of-personal-information":
      "2. Collecte des Informations Personnelles",
  "yout-personal-information":
      "Les informations personnelles que vous fournissez lors de la création de votre compte, telles que votre nom, prénom et date de naissance, sont strictement confidentielles. Elles seront accessibles uniquement par vous et par les médecins avec lesquels vous avez pris rendez-vous.",
  "medical-records": "3. Gestion des Dossiers Médicaux",
  "the-doctors-you-consult-through-medix-can-manage-your-medical-file":
      "Les médecins que vous consultez via Medix peuvent gérer votre dossier médical et vous proposer des rendez-vous de suivi médical. Ils sont les seuls, en dehors de vous-même, à avoir accès à vos informations médicales.",
  "privacy-and-Security": "4. Confidentialité et Sécurité",
  "your-personal-and-medical-information":
      "Vos informations personnelles et médicales"
};
