final Map<String, String> profileFR = {
  "favorites": "Favoris",
  "edit-profile": "Modifier le profil",
  "edit-phone": "Changer le numéro de téléphone",
  "edit-password": "Changer le mot de passe",
  "my-reviews": "Mes avis",
  "settings": "Paramètres",
  "profile": "Profil",
  "logout": "Se déconnecter",
  "delete-account": "Supprimer le compte",
  "warning": "Attention",
  "warning-info":
      "La suppression de votre compte est permanente. Êtes-vous sûr(e) ?",
  "delete": "Supprimer",
  "current-password": "Mot de passe actuel",
  "new-password": "Nouveau mot de passe",
  "confirm-password": "Confirmer le nouveau mot de passe",
  "password-not-match": "Les mots de passe ne correspondent pas",
  "update": "Mettre à jour",
  "phone-number": "Numéro de téléphone",
  "enter-your-firstname": "Entrez votre prénom",
  "last-name": "Nom de famille",
  "enter-your-last-name": "Entrez votre nom de famille",
  "city": "Ville",
  "enter-your-city": "Votre ville",
  "gender": "Sexe",
  "enter-your-address": "Votre adresse",
  "birthday": "Anniversaire",
  "saved": "Enregistré",
  "verification": "Vérification",
  "dark-mode": "Mode sombre",
  "home": "Accueil",
  "my-appointments": "Mes rendez-vous"
};
