final Map<String, String> specialitiesFR = {
  "All": "Tous",
  "Allergology": "Allergie et immunologie",
  "Anesthesiology": "Anesthésie-Réanimation",
  "Cardiology": "Cardiologie",
  "Dermatology": "Dermatologie",
  "Endocrinology": "Endocrinologie",
  "Gastroenterology": "Gastro-entérologie",
  "Geriatrics": "Gériatrie",
  "Gynecology": "Gynécologie",
  "Hematology": "Hématologie",
  "Hepatology": "Hépatologie",
  "Immunology": "Allergie et immunologie",
  "Emergency medicine": "Médecine d'urgence",
  "General medicine": "Médecine générale",
  "Internal Medicine": "Médecine interne",
  "Neonatology": "Néonatologie",
  "Nephrology": "Néphrologie",
  "Neurology": "Neurologie",
  "Oncology": "Oncologie",
  "Pediatrics": "Pédiatrie",
  "Pneumology": "Pneumologie",
  "Psychiatry": "Psychiatrie",
  "Specialties": "Spécialités"
};
