final Map<String, String> authEN = {
  "login-to-your-account": "Log in to your account",
  "your-phone-number": "Phone number",
  "phone-number-required": "Phone number is required",
  "your-password": "Password",
  "password": "Password",
  "password-not-match": "Incorrect password",
  "password-min": "The password must contain at least @min characters",
  "your-birthday": "Birthday",
  "firstname": "First name",
  "your-informations": "Your information",
  "create-your-account": "Create an account",
  "your-gender": "Gender",
  "login-btn": "Login",
  "dont-have-account": "Don't have an account yet?",
  "login-create-account": "Sign up",
  "term-and-condition":
      "I accept the terms of use, the privacy policy, and the terms of service",
  "term-accepted-required-checkbox": "This field is required",
  "already-registered": "Already registered?",
  "have-account-signin": "Sign in",
  "something-went-wrong-title": "A problem has occurred",
  "something-went-wrong": "An error has occurred",
  "something-went-wrong-try": "An error has occurred, please try again",
  "success": "Success",
  "error": "Error",
  "finished": "Finished",
  "suspended": "Suspended",
  "canceled": "Canceled",
  "completed": "Completed",
  "login-success": "Login successful",
  "profile-update-success": "Profile updated successfully",
  "invalid-phone-number": "Invalid phone number",
  "upload-pending": "Uploading...",
  "man": "Man",
  "woman": "Woman",
  "Nouakchott": "Nouakchott",
  "Nouadhibou": "Nouadhibou",
  "Rosso": "Rosso",
  "Boghé": "Boghé",
  "Kiffa": "Kiffa",
  "Zouerate": "Zouerate",
  "Kaédi": "Kaédi",
  "Boutilimit": "Boutilimit",
  "Atar": "Atar",
  "Sélibaby": "Sélibaby",
  "Aleg": "Aleg",
  "Akjoujt": "Akjoujt",
  "Tidjikja": "Tidjikja",
  'resend': 'Resend',
  'resend-in': 'Resend in',
  'i-did-not-receive-any-code': "I didn't receive any code?",
  'verify-your-phone-number': 'Verify Your Phone Number',
  'otp-send-to-your-phone-number':
      'A verification code has been sent to your phone number. Please enter it below.',
  "password-required": "Password required",
  'password-updated': 'Password updated',
  'can-not-resend-otp': 'Unable to resend OTP',
  'tape-otp': 'Enter OTP',
  'phone-number-already-used':
      'The phone number has already been used by another user.',
  'are-you-sur-to-canceled':
      "Are you sure you want to cancel your appointment?",
  'yes': 'Yes',
  'reschedule': 'Reschedule',
  'reschedule-your-appointment': 'Reschedule your appointment',
  'reschedule-appointment': 'Reschedule appointment',
  'reset-your-password': 'Reset your password',
  'forget-password': "Forgot password?",
  'reset': 'Reset',
  'appointment-reschedule-success':
      'Your appointment has been rescheduled and is awaiting confirmation from the doctor.',
  'appointment-delete-success':
      'Your appointment has been cancelled successfully.'
};
