final Map<String, String> authEN = {
  "login-to-your-account": "Log in to your account",
  "your-phone-number": "Phone number",
  "phone-number-required": "Phone number is required",
  "your-password": "Password",
  "password": "Password",
  "password-not-match": "Incorrect password",
  "password-min": "The password must contain at least @min characters",
  "your-birthday": "Birthday",
  "firstname": "First name",
  "your-informations": "Your information",
  "create-your-account": "Create an account",
  "your-gender": "Gender",
  "login-btn": "Login",
  "dont-have-account": "Don't have an account yet?",
  "login-create-account": "Sign up",
  "term-and-condition":
      "I have read and accept the privacy policy and terms of use.",
  "term-accepted-required-checkbox": "This field is required",
  "already-registered": "Already registered?",
  "have-account-signin": "Sign in",
  "something-went-wrong-title": "A problem has occurred",
  "something-went-wrong": "An error has occurred",
  "something-went-wrong-try": "An error has occurred, please try again",
  "success": "Success",
  "error": "Error",
  "finished": "Finished",
  "suspended": "Suspended",
  "canceled": "Canceled",
  "completed": "Completed",
  "login-success": "Login successful",
  "profile-update-success": "Profile updated successfully",
  "invalid-phone-number": "Invalid phone number",
  "upload-pending": "Uploading...",
  "man": "Man",
  "woman": "Woman",
  "Nouakchott": "Nouakchott",
  "Nouadhibou": "Nouadhibou",
  "Rosso": "Rosso",
  "Boghé": "Boghé",
  "Kiffa": "Kiffa",
  "Zouerate": "Zouerate",
  "Kaédi": "Kaédi",
  "Boutilimit": "Boutilimit",
  "Atar": "Atar",
  "Sélibaby": "Sélibaby",
  "Aleg": "Aleg",
  "Akjoujt": "Akjoujt",
  "Tidjikja": "Tidjikja",
  'resend': 'Resend',
  'resend-in': 'Resend in',
  'i-did-not-receive-any-code': "I didn't receive any code?",
  'verify-your-phone-number': 'Verify Your Phone Number',
  'otp-send-to-your-phone-number':
      'A verification code has been sent to your phone number. Please enter it below.',
  "password-required": "Password required",
  'password-updated': 'Password updated',
  'can-not-resend-otp': 'Unable to resend OTP',
  'tape-otp': 'Enter OTP',
  'phone-number-already-used':
      'The phone number has already been used by another user.',
  'are-you-sur-to-canceled':
      "Are you sure you want to cancel your appointment?",
  'yes': 'Yes',
  'reschedule': 'Reschedule',
  'reschedule-your-appointment': 'Reschedule your appointment',
  'reschedule-appointment': 'Reschedule appointment',
  'reset-your-password': 'Reset your password',
  'forget-password': "Forgot password?",
  'reset': 'Reset',
  'appointment-reschedule-success':
      'Your appointment has been rescheduled and is awaiting confirmation from the doctor.',
  'appointment-delete-success':
      'Your appointment has been cancelled successfully.',
  "medix-term-and-condition": "Terms of Use and Privacy Policy of Medix",
  "accept-term-and-condition": "1. Acceptance of Terms",
  "if-create-account-in-medix":
      "By creating an account on the Medix application, you agree to comply with our terms of use and privacy policy. Medix allows you to search for and book appointments with doctors of various specialties.",
  "collection-of-personal-information": "2. Collection of Personal Information",
  "yout-personal-information":
      "The personal information you provide when creating your account, such as your first name, last name, and date of birth, is strictly confidential. It will be accessible only by you and the doctors with whom you have made appointments.",
  "medical-records": "3. Management of Medical Records",
  "the-doctors-you-consult-through-medix-can-manage-your-medical-file":
      "The doctors you consult through Medix can manage your medical file and offer you medical follow-up appointments. They are the only ones, besides yourself, who have access to your medical information.",
  "privacy-and-Security": "4. Privacy and Security",
  "your-personal-and-medical-information":
      "Your personal and medical information",
  "welcome-to-medix": "Welcome to Medix",
  "book-appointment-one-click":
      "Find a doctor and book your appointment with just one click.",
  "for-find-a-doctor-location": "To find the closest doctors to you.",
  "for-find-a-doctor-location-location-permission-required":
      "Access to your location data is required to enable doctor geolocation in this app.",
  "location-not-used-background":
      "It will not collect your location in the background",
  "for-receive-realtime-notifications":
      "To receive real-time notifications about your medical appointments.",
  "please-guaranted-notifications-permission": "Please allow notifications",
  "guaranted-notifications": "Allow notifications",
  "log-in-or-sign-up": "Log in or sign up.",
  "no-thanks": "No thanks"
};
