final Map<String, String> doctorEN = {
  'select-appointment-time': 'Select Appointment Time',
  'not-available': 'Not Available',
  'book-appointment': 'Book Now',
  'consultation-price': 'Consultation Fee',
  'appointment-reason': 'Reason for Appointment',
  'next': 'Next',
  'doctor-experience': 'Experience',
  'doctor-patients': 'Patients',
  'doctor-about': 'About Me',
  'view-more': 'View More',
  'view-timetable': 'See Schedule',
  'reviews': 'Reviews',
  'doctor-profil': 'Doctor Profile',
  'timetable': 'Schedule',
  'about-doctor': 'About Me',
  'search-doctor': "Search Doctor",
  'filter-speciality': "Filter by Specialty",
  'apply': "Apply Filters",
  'doctors-specialities': "Doctors' Specialties",
  'see-all': 'See All',
  'all-specialities': 'All Specialties',
  'no-patients-reviews': "No Patient Reviews Yet",
  "top-doctors": "Top doctors",

  //
  "review-update": "Review updated, thank you.",
  "thank-for-your-feedback": "Thank you for sharing your feedback",
  "review-delete": "Review deleted",
  "submit": "Submit",
  "your-review": "Your review",
  "update-this-review": "Update this review",
  "delete-this-review": "Delete this review",
  "qualifications": "Qualifications",
};
