final Map<String, String> profileEN = {
  'favorites': 'Favorites',
  'edit-profile': 'Edit Profile',
  'edit-phone': 'Change Phone Number',
  'edit-password': 'Change Password',
  'my-reviews': 'My Reviews',
  'settings': 'Settings',
  'profile': 'Profile',
  'logout': 'Logout',
  'delete-account': 'Delete Account',
  'warning': 'Warning',
  'warning-info': 'Deleting your account is permanent. Are you sure?',
  'delete': 'Delete',
  'current-password': 'Current Password',
  'new-password': 'New Password',
  'confirm-password': 'Confirm New Password',
  'password-not-match': 'Passwords do not match',
  'update': 'Update',
  'phone-number': 'Phone Number',
  'enter-your-firstname': 'Enter First Name',
  'last-name': 'Last Name',
  'enter-your-last-name': 'Enter Last Name',
  'city': 'City',
  'enter-your-city': 'Your City',
  'gender': 'Gender',
  'enter-your-address': 'Your Address',
  'birthday': 'Birthday',
  'saved': 'Saved',
  'verification': 'Verification',
  'dark-mode': 'Dark Mode',
  'home': 'Home',
  'my-appointments': 'My Appointments',
};
