final Map<String, String> specialitiesEN = {
  'All': 'All',
  'Allergology': 'Allergy and Immunology',
  'Anesthesiology': 'Anesthesiology',
  'Cardiology': 'Cardiology',
  'Dermatology': 'Dermatology',
  'Endocrinology': 'Endocrinology',
  'Gastroenterology': 'Gastroenterology',
  'Geriatrics': 'Geriatrics',
  'Gynecology': 'Gynecology',
  'Hematology': 'Hematology',
  'Hepatology': 'Hepatology',
  'Immunology': 'Allergy and Immunology',
  'Emergency medicine': 'Emergency Medicine',
  'General medicine': 'General Practice',
  'Internal Medicine': 'Internal Medicine',
  'Neonatology': 'Neonatology',
  'Nephrology': 'Nephrology',
  'Neurology': 'Neurology',
  'Oncology': 'Oncology',
  'Pediatrics': 'Pediatrics',
  'Pneumology': 'Pulmonology',
  'Psychiatry': 'Psychiatry',
  "Specialties": "Specialties"
};
