final Map<String, String> appointmentAR = {
  "appointment": "موعد",
  "appointment-details": "تفاصيل الموعد",
  "appointment-motif": "سبب الموعد",
  "appointment-accepted-message": "رسالة تأكيد الطبيب",
  "appointment-refused-message": "سبب الرفض",
  "appointment-pending": "معلق",
  "appointment-accepted": "مقبول",
  "appointment-denied": "مرفوض",
  "appointment-place": "المكان",
  "appointment-address": "العنوان",
  "appointment-date": "التاريخ",
  "appointment-price": "سعر الموعد",
  "appointment-payment": "الدفع",
  "appointment-payment-true": "مدفوع",
  "appointment-payment-false": "غير مدفوع",
  "patient-appointments": "مواعيدي",
  "patient-appointments-empty-pending": "لا توجد مواعيد معلقة",
  "patient-appointments-empty-acceted": "لا يوجد مواعيد مقبولة حتى الآن",
  "patient-appointments-empty-denied": "لا توجد مواعيد مرفوضة",
  "patient-appointments-empty-finished": "يتم عرض موعدك المكتمل هنا",
  "appointment-finished": "انتهى",
  "doctor-not-available-on-this-day":
      "الطبيب غير متوفر في هذا اليوم. يرجى اختيار تاريخ آخر.",
  "please-select-date-and-hour-for-appointment":
      "يرجى اختيار تاريخ ووقت لموعدك.",
  "date-chosen-has-passed":
      "التاريخ المختار قد مضى. يرجى اختيار تاريخ مستقبلي.",
  "close": "اغلاق",
  "date-and-hour-format": "في @date في @hour",
  "year": "سنة",
  "years": "سنوات",
  "month": "شهر",
  "months": "شهور",
  "day": "يوم",
  "days": "أيام",
  "hour": "ساعة",
  "minutes": "دقائق",
  "minute": "دقيقة",
  'secondes': 'ثوانٍ',
  'seconde': 'ثانية',
  'times-ago': 'منذ @times',
  'appointment-saved-and-awaiting': "تم تسجيل موعدك وفي انتظار رد الطبيب.",

  //
  "appointment-session-ended": "تم إنهاء موعدك بنجاح.",
  "what-is-your-experience": "كيف كانت تجربتك؟ يرجى تقييم طبيبك ومشاركة رأيك.",
  "write-your-review": "اكتب مراجعة"
};
