final Map<String, String> authAR = {
  "login-to-your-account": "تسجيل الدخول إلى حسابك",
  "your-phone-number": "رقم الهاتف",
  "phone-number-required": "رقم الهاتف مطلوب",
  "your-password": "كلمة المرور",
  "password": "كلمة المرور",
  "password-not-match": "كلمة مرور غير صحيحة",
  "password-min": "يجب أن تحتوي كلمة المرور على @min حرفًا على الأقل",
  "your-birthday": "عيد الميلاد",
  "firstname": "الاسم الأول",
  "your-informations": "معلوماتك",
  "create-your-account": "إنشاء حساب",
  "your-gender": "الجنس",
  "login-btn": "تسجيل الدخول",
  "dont-have-account": "ليس لديك حساب؟",
  "login-create-account": "اشتراك",
  "term-and-condition": "أوافق على شروط الخدمة وسياسة الخصوصية وشروط الاستخدام",
  "term-accepted-required-checkbox": "هذا الحقل مطلوب",
  "already-registered": "مسجل مسبقا؟",
  "have-account-signin": "تسجيل الدخول",
  "something-went-wrong-title": "حدث خطأ ما",
  "something-went-wrong": "حدث خطأ",
  "something-went-wrong-try": "حدث خطأ ، يرجى المحاولة مرة أخرى",
  'success': 'نجاح',
  'error': 'خطأ',
  'finished': 'تم الانتهاء',
  'suspended': 'معلق',
  'canceled': 'ملغى',
  'completed': 'مكتمل',
  'login-success': 'تم تسجيل الدخول بنجاح',
  'profile-update-success': 'تم تحديث ملفك الشخصي بنجاح',
  'invalid-phone-number': 'رقم الهاتف هذا غير صالح',
  'upload-pending': 'قيد الانتظار...',
  'man': 'رجل',
  'woman': 'امرأة',
  'Nouakchott': 'نواكشوط',
  'Nouadhibou': 'نواذيبو',
  'Rosso': 'روسو',
  'Boghé': 'بوغي',
  'Kiffa': 'كيفة',
  'Zouerate': 'زويرات',
  'Kaédi': 'كيهيدي',
  'Boutilimit': 'بوتلميت',
  'Atar': 'أطار',
  'Sélibaby': 'سيلبابي',
  'Aleg': 'ألاك',
  'Akjoujt': 'أكجوجت',
  'Tidjikja': 'تجكجة',
  'resend': 'إعادة إرسال',
  'resend-in': 'إعادة إرسال في',
  'i-did-not-receive-any-code': "لم أتلق أي رمز؟",
  'verify-your-phone-number': 'تحقق من رقم هاتفك',
  'otp-send-to-your-phone-number':
      'تم إرسال رمز التحقق إلى رقم هاتفك. يرجى إدخاله أدناه.',
  "password-required": "كلمة المرور مطلوبة",
  'password-updated': 'تم تحديث كلمة المرور',
  'can-not-resend-otp': 'لا يمكن إعادة إرسال رمز OTP',
  'tape-otp': 'أدخل رمز OTP',
  'phone-number-already-used': 'تم استخدام رقم الهاتف من قبل مستخدم آخر.',
  'are-you-sur-to-canceled': "هل أنت متأكد من إلغاء موعدك؟",
  'yes': 'نعم',
  'reschedule': 'إعادة الجدولة',
  'reschedule-your-appointment': 'إعادة جدولة موعدك',
  'reschedule-appointment': 'إعادة جدولة الموعد',
  'reset-your-password': 'إعادة تعيين كلمة المرور',
  'forget-password': "هل نسيت كلمة المرور؟",
  'reset': 'إعادة تعيين',
  'appointment-reschedule-success':
      'تم إعادة جدولة موعدك بنجاح وينتظر تأكيد الطبيب.',
  'appointment-delete-success': 'تم إلغاء موعدك بنجاح.'
};
