final Map<String, String> doctorAR = {
  "select-appointment-time": "اختيار وقت الموعد",
  "not-available": "غير متوفر",
  "book-appointment": "احجز الآن",
  "consultation-price": "رسوم الاستشارة",
  "appointment-reason": "سبب الموعد",
  "next": "التالي",
  "doctor-experience": "خبرة",
  "doctor-patients": "مرضى",
  "doctor-about": "عنّي",
  "view-more": "عرض المزيد",
  "view-timetable": "عرض الجدول الزمني",
  "reviews": "المراجعات",
  "doctor-profil": "ملف تعريف الطبيب",
  "timetable": "الجدول الزمني",
  "about-doctor": "عنّي",
  "search-doctor": "البحث عن طبيب",
  "filter-speciality": "التصفية حسب التخصص",
  "apply": "تطبيق الفلاتر",
  "doctors-specialities": "تخصصات الأطباء",
  "see-all": "عرض الكل",
  "all-specialities": "جميع التخصصات",
  "no-patients-reviews": "لا توجد مراجعات للمرضى حتى الآن",
  "top-doctors": "كبار الأطباء",

  //
  "review-update": "تم تحديث المراجعة، شكرًا لك.",
  "thank-for-your-feedback": "شكرًا لك على مشاركة ملاحظاتك",
  "review-delete": "تم حذف المراجعة",
  "submit": "إرسال",
  "your-review": "مراجعة",
  "update-this-review": "تحديث هذه المراجعة",
  "delete-this-review": "حذف هذه المراجعة"
};
