final Map<String, String> profileAR = {
  "favorites": "المفضلة",
  "edit-profile": "تعديل الملف الشخصي",
  "edit-phone": "تغيير رقم الهاتف",
  "edit-password": "تغيير كلمة المرور",
  "my-reviews": "المراجعات الخاصة بي",
  "settings": "الإعدادات",
  "profile": "الملف الشخصي",
  "logout": "تسجيل الخروج",
  "delete-account": "حذف الحساب",
  "warning": "تحذير",
  "warning-info": "حذف حسابك نهائي. هل أنت متأكد؟",
  "delete": "حذف",
  "current-password": "كلمة المرور الحالية",
  "new-password": "كلمة مرور جديدة",
  "confirm-password": "تأكيد كلمة المرور الجديدة",
  "password-not-match": "كلمات المرور غير متطابقة",
  "update": "تحديث",
  "phone-number": "رقم الهاتف",
  "enter-your-firstname": "أدخل الاسم الأول",
  "last-name": "اللقب",
  "enter-your-last-name": "أدخل لقبك",
  "city": "مدينة",
  "enter-your-city": "مدينتك",
  "gender": "الجنس",
  "enter-your-address": "عنوانك",
  "birthday": "عيد الميلاد",
  "saved": "حفظ",
  "verification": "التحقق",
  "dark-mode": "الوضع المظلم",
  "home": "الرئيسية",
  "my-appointments": "مواعيدي"
};
