final Map<String, String> specialitiesAR = {
  "All": "الكل",
  "Allergology": "الحساسية والمناعة",
  "Anesthesiology": "طب التخدير والإنعاش",
  "Cardiology": "أمراض القلب",
  "Dermatology": "أمراض الجلد",
  "Endocrinology": "الغدد الصماء",
  "Gastroenterology": "أمراض الجهاز الهضمي",
  "Geriatrics": "طب الشيخوخة",
  "Gynecology": "أمراض النساء",
  "Hematology": "أمراض الدم",
  "Hepatology": "أمراض الكبد",
  "Immunology": "الحساسية والمناعة",
  "Emergency medicine": "طب الطوارئ",
  "General medicine": "الطب العام",
  "Internal Medicine": "الطب الباطني",
  "Neonatology": "حديثي الولادة",
  "Nephrology": "أمراض الكلى",
  "Neurology": "أمراض الأعصاب",
  "Oncology": "الأورام",
  "Pediatrics": "طب الأطفال",
  "Pneumology": "أمراض الرئة",
  "Psychiatry": "الطب النفسي",
  "Specialties": "التخصصات"
};
